apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      name: guestbook
      labels:
        app: guestbook
    spec:
      containers:
      - image: kangbohyun/cicd_guestbook:20250813080643_1
        name: sb-guestbook
        envFrom:
        - configMapRef:
            name: guestbook-cm
